name: Train Student Model

on:
  push:
    branches:
      - k8s-model-deployment

  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build Docker image
        run: |
          docker build -t image1 .

      - name: docker tag
        run:
          docker tag image1 anusha414/anusharepo1:${GITHUB_SHA::7}-${{github.run_id}}

      - name: Docker Hub Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: docker push
        run: |
          docker push anusha414/anusharepo1:${GITHUB_SHA::7}-${{github.run_id}}

      - name: Set image name
        run: |
          SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-7)
          export IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/anusharepo1:${SHORT_SHA}-${GITHUB_RUN_ID}"
          envsubst < ./k8s/deployment.yaml > ./k8s/deployment.yaml.tmp && mv ./k8s/deployment.yaml.tmp ./k8s/deployment.yaml
          cat ./k8s/deployment.yaml

      - name: Save Docker image
        run: |
          docker save image1 -o my-app.tar

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./my-app.tar
