name: Train Student Model

on:
  push:
    branches:
      - k8s-model-deployment

  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build Docker image
        run: |
          docker build -t image1 .

      - name: Save Docker image
        run: |
          docker save image1 -o my-app.tar

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./my-app.tar
