name: Train Student Model

on:
  push:
    branches:
      - local-model-deployment

  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training Script
        run: |
          python model/train.py

      - name: Run the API
        run: |
          python app.py

      - name: Upload Trained Model
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: model/artifacts
