name: Install mlflow on github runner and add experiment tracking
on:
  push:
    branches:
      - model-create

  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute mlflow
        run: |
          mkdir -p mlruns
          mlflow server \
          --host 0.0.0.0 \
          --port 5000 \
          --backend-store-uri sqlite:///mlflow.db \
          --default-artifact-root ./mlruns

      - name: Run Training Script
        run: |
          python train_model.py

      - name: Upload Trained Model
        uses: actions/upload-artifact@v4
        with:
          name: student-pass-model
          path: student_pass_model.pkl
